apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aporia-importer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aporia-importer.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Values.importer.config | indent 4 }}
  {{- if .Values.autoscaling.enabled }}
  worker-spec.yml: |-
    kind: Pod
    metadata:
      namespace: {{ .Release.Namespace }}
    {{- with .Values.autoscaling.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "aporia-importer.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - image: "{{ .Values.autoscaling.worker.image.repository }}:{{ .Values.autoscaling.worker.image.tag }}"
        imagePullPolicy: {{ .Values.autoscaling.worker.image.pullPolicy }}
        args:
          - dask-worker
          - --no-dashboard
          {{- if .Values.autoscaling.worker.resources.limits }}
          - --nthreads
          - {{ .Values.autoscaling.worker.threadsPerWorker | quote }}
          - --memory-limit
          - {{ .Values.autoscaling.worker.resources.limits.memory | quote }}
          {{- end }} 
          - --death-timeout
          - {{ .Values.autoscaling.worker.deathTimeout | quote }}
        name: dask
        env:
          - name: EXTRA_PIP_PACKAGES
            value: aporia[all] pyarrow s3fs git+https://github.com/dask/distributed pandas==1.3.1 dask_kubernetes
        resources:
          {{- toYaml .Values.autoscaling.worker.resources | nindent 10 }}
      {{- with .Values.autoscaling.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoscaling.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoscaling.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.autoscaling.worker.serviceAccountName }}
        serviceAccountName: {{ .Values.autoscaling.worker.serviceAccountName | quote }}
      {{- end }}
  {{- end }}